version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"         # container:host port binding
    volumes:
      - .:/code             # mount current directory into container
    environment:
      - DEBUG=True          # runtime environment variable
    networks:
      - tasknet             # custom docker network
networks:
  tasknet:
    driver: bridge
